### ISSUE TITLE
请问ksp的log具体是在哪看的？

### ISSUE THREAD

**Issue by Anivie** [kotlin-orm/ktorm-ksp#1]
build目录下的log目录都是空的。。。
报错是：
```
[ksp] java.util.NoSuchElementException: Sequence is empty.
	at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:112)
	at org.ktorm.ksp.compiler.KtormProcessor$EntityVisitor.visitClassDeclaration(KtormProcessorProvider.kt:217)
	at org.ktorm.ksp.compiler.KtormProcessor$EntityVisitor.visitClassDeclaration(KtormProcessorProvider.kt:196)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:136)
	at org.ktorm.ksp.compiler.KtormProcessor.process(KtormProcessorProvider.kt:90)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:237)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:235)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:330)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:235)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:264)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:255)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:157)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1642)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:598)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:844)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:721)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:720)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by lookup-cat** [comment]
执行 ```gradle build -i``` 可以在控制台看到ksp的日志.
不过你这个报错的问题 能否提供一下代码?

**Comment by Anivie** [comment]
> 执行 `gradle build -i` 可以在控制台看到ksp的日志. 不过你这个报错的问题 能否提供一下代码?

错误是：
```
i: [ksp] loaded provider(s): [org.ktorm.ksp.compiler.KtormProcessorProvider]
i: [ksp] create ktorm symbolProcessor
i: [ksp] start ktorm ksp processor
i: [ksp] ktormKspConfigSymbols:[]
i: [ksp] config:CodeGenerateConfig(allowReflectionCreateEntity=true, enumConverter=null, singleTypeConverters={}, configDependencyFile=null, namingStrategy=null, localNamingStrategy=null, extensionGenerator=ExtensionGeneratorConfig(enableSequenceOf=true, enableClassEntitySequenceAddFun=true, enableClassEntitySequenceUpdateFun=true))
i: [ksp] symbols:[Manager, Employee, Book]
e: [ksp] java.util.NoSuchElementException: Sequence is empty.
        at kotlin.sequences.SequencesKt___SequencesKt.first(_Sequences.kt:112)
        at org.ktorm.ksp.compiler.KtormProcessor$EntityVisitor.visitClassDeclaration(KtormProcessorProvider.kt:217)
        at org.ktorm.ksp.compiler.KtormProcessor$EntityVisitor.visitClassDeclaration(KtormProcessorProvider.kt:196)
        at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:136)
        at org.ktorm.ksp.compiler.KtormProcessor.process(KtormProcessorProvider.kt:90)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:237)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:235)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:330)
        at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:235)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
        at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:264)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:255)        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
        at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:157)
        at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
        at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
        at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
        at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1642)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
        at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
        at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
        at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:889)

e: Error occurred in KSP, check log for detail
```

我不是很了解ksp，没看出来具体是哪里触发的错误，我用到这个插件的地方是：
```
    @Serializable
    @Tables("employee")
    data class Employee(
        val id: Int,
        var name: String,
        var pass: String,
        var identity: String,
        var email: String,
        var phone: String,
        var idNumber: String,

        @Contextual
        var date: LocalDate
    )
```
Serializable是kotlinx官方序列化库提供的，我用来序列化为protobuf进行网络传输

**Comment by Anivie** [comment]
> 执行 `gradle build -i` 可以在控制台看到ksp的日志. 不过你这个报错的问题 能否提供一下代码?

关键我本来是能正常跑的，而且试了挺多功能，然后就想上我的一个项目里试试，结果把代码改完不知道为什么一构建就是这个错误，把Serializable注释掉也不行

**Comment by Anivie** [comment]
> 执行 `gradle build -i` 可以在控制台看到ksp的日志. 不过你这个报错的问题 能否提供一下代码?

反复clean，build之后又出了个新的报错，不知道对您定位问题有没有帮助
```
[ksp] java.io.IOException: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile.loadChunk(CompressedAppendableFile.java:185)
	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile.access$100(CompressedAppendableFile.java:30)
	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile$FileChunkReadCache.get(CompressedAppendableFile.java:463)
	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile$SegmentedChunkInputStream.read(CompressedAppendableFile.java:515)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:201)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage$ReaderOverCompressedFile.get(PersistentHashMapValueStorage.java:777)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMapValueStorage.readBytes(PersistentHashMapValueStorage.java:547)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:655)
	at org.jetbrains.kotlin.com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:602)
	at org.jetbrains.kotlin.incremental.storage.CachingLazyStorage.get(CachingLazyStorage.kt:69)
	at com.google.devtools.ksp.FileToSymbolsMap.get(Incremental.kt:74)
	at com.google.devtools.ksp.DirtinessPropagator.visit(Incremental.kt:765)
	at com.google.devtools.ksp.DirtinessPropagator.propagate(Incremental.kt:782)
	at com.google.devtools.ksp.IncrementalContext.calcDirtyFiles(Incremental.kt:394)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$1.invoke(KotlinSymbolProcessingExtension.kt:164)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$1.invoke(KotlinSymbolProcessingExtension.kt:157)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:330)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:157)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:264)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:255)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:157)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:94)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1642)
	at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:718)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:889)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at org.jetbrains.kotlin.net.jpountz.util.SafeUtils.checkRange(SafeUtils.java:24)
	at org.jetbrains.kotlin.net.jpountz.util.UnsafeUtils.checkRange(UnsafeUtils.java:56)
	at org.jetbrains.kotlin.net.jpountz.lz4.LZ4JavaUnsafeFastDecompressor.decompress(LZ4JavaUnsafeFastDecompressor.java:23)
	at org.jetbrains.kotlin.net.jpountz.lz4.LZ4FastDecompressor.decompress(LZ4FastDecompressor.java:107)
	at org.jetbrains.kotlin.com.intellij.util.CompressionUtil.readCompressedWithoutOriginalBufferLength(CompressionUtil.java:94)
	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile.decompress(CompressedAppendableFile.java:343)
	at org.jetbrains.kotlin.com.intellij.util.io.CompressedAppendableFile.loadChunk(CompressedAppendableFile.java:173)
	... 47 more
```

**Comment by lookup-cat** [comment]
我看日志是有三个类使用了@Table注解 Manager, Employee, Book
试试看是每个类加上@Table都会触发报错, 还是只有某一个会?
还有就是这几个类都定义在同一个文件还是在不同文件的呢? 
项目里除了ktorm-ksp和kotlinx-serialization 还有其他插件吗?

**Comment by Anivie** [comment]
> 

现在是任何一个table都会报这个错了。。。
项目使用了四个插件：
    id 'com.github.johnrengelman.shadow' version "7.1.0"
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.7.0'
    id 'org.jetbrains.kotlin.jvm' version '1.7.0'
    id 'com.google.devtools.ksp' version '1.7.0-1.0.6'

**Comment by Anivie** [comment]
> 我看日志是有三个类使用了@table注解 Manager, Employee, Book 试试看是每个类加上@table都会触发报错, 还是只有某一个会? 还有就是这几个类都定义在同一个文件还是在不同文件的呢? 项目里除了ktorm-ksp和kotlinx-serialization 还有其他插件吗?

现在是任何一个table都会报这个错了。。。
定义在同一个类里，那个类是个抽象类，数据库的控制类通过继承他直接获得这些实体
项目使用了四个插件：
id 'com.github.johnrengelman.shadow' version "7.1.0"
id 'org.jetbrains.kotlin.plugin.serialization' version '1.7.0'
id 'org.jetbrains.kotlin.jvm' version '1.7.0'
id 'com.google.devtools.ksp' version '1.7.0-1.0.6'

**Comment by lookup-cat** [comment]
你好, 我这边试了还是复现不出来, 方便加下QQ吗? 我的QQ是641571835

**Comment by Anivie** [comment]
> 你好, 我这边试了还是复现不出来, 方便加下QQ吗? 我的QQ是641571835

我把data class单独抽出来作另一个抽象类后程序运行正常了。。。

**Comment by lookup-cat** [comment]
可以发下之前触发异常的完整代码吗?

**Comment by Anivie** [comment]
可以的，在我这里无法构建，但是不确定是代码问题还是其他的环境（玄学）问题：
```
package ink.bluecloud.DataBase.Mysql

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import org.ktorm.ksp.api.PrimaryKey
import org.ktorm.schema.*
import java.time.LocalDate

abstract class KtormData {
    object ManagerList : Table<Nothing>("manager_list") {
        val name = varchar("name")
        val email = varchar("email")
        val date = date("date")
    }

    object EmployeeList : Table<Nothing>("employee") {
        val id = int("id").primaryKey()
        val name = varchar("name")
        val pass = varchar("pass")

        val identity = varchar("identity")

        val email = varchar("email")
        val phone = varchar("phone")
        val idNumber = varchar("idNumber")

        val date = date("date")
    }

    object BookInfo : Table<Nothing>("book_info") {
        val bookId = int("book_id").primaryKey()
        val bookCode = varchar("book_code")
        val bookTitle = varchar("book_title")
        val bookArtist = varchar("book_artist")
        val bookMainType = varchar("book_main_type")
        val bookSecondType = varchar("book_second_type")
        val bookDescription = text("book_description")
        val bookPrice = float("book_price")
        val bookBorrowingAllowed = boolean("book_borrowilowed")
        val bookBan = boolean("book_ban")
        val bookHighValue = boolean("book_high_value")
        val bookOperator = varchar("book_operator")
    }

    @Serializable
    @org.ktorm.ksp.api.Table("manager_list")
    data class Manager(
        val name: String,
        val email: String,

        @Contextual
        val date: LocalDate
    )

    @Serializable
    @org.ktorm.ksp.api.Table("employee")
    data class Employee(
        val id: Int,
        var name: String,
        var pass: String,
        var identity: String,
        var email: String,
        var phone: String,
        var idNumber: String,

        @Contextual
        var date: LocalDate
    )

    @Serializable
    @org.ktorm.ksp.api.Table("book_info")
    data class Book(
        @PrimaryKey
        val bookId: Int,

        var bookCode: String,
        var bookTitle: String,
        var bookArtist: String,

        var bookMainType: String,
        var bookSecondType: String,

        var bookDescription: String,
        var bookPrice: Float,

        var bookBorrowingAllowed: Boolean,
        var bookBan: Boolean,
        var bookHighValue: Boolean,

        var bookOperator: String,
    )
}
```

**Comment by Anivie** [comment]
> 可以发下之前触发异常的完整代码吗?

可以的，在我这里无法构建，但是不确定是代码问题还是其他的环境（玄学）问题：
```
package ink.bluecloud.DataBase.Mysql

import kotlinx.serialization.Contextual
import kotlinx.serialization.Serializable
import org.ktorm.ksp.api.PrimaryKey
import org.ktorm.schema.*
import java.time.LocalDate

abstract class KtormData {
    object ManagerList : Table<Nothing>("manager_list") {
        val name = varchar("name")
        val email = varchar("email")
        val date = date("date")
    }

    object EmployeeList : Table<Nothing>("employee") {
        val id = int("id").primaryKey()
        val name = varchar("name")
        val pass = varchar("pass")

        val identity = varchar("identity")

        val email = varchar("email")
        val phone = varchar("phone")
        val idNumber = varchar("idNumber")

        val date = date("date")
    }

    object BookInfo : Table<Nothing>("book_info") {
        val bookId = int("book_id").primaryKey()
        val bookCode = varchar("book_code")
        val bookTitle = varchar("book_title")
        val bookArtist = varchar("book_artist")
        val bookMainType = varchar("book_main_type")
        val bookSecondType = varchar("book_second_type")
        val bookDescription = text("book_description")
        val bookPrice = float("book_price")
        val bookBorrowingAllowed = boolean("book_borrowilowed")
        val bookBan = boolean("book_ban")
        val bookHighValue = boolean("book_high_value")
        val bookOperator = varchar("book_operator")
    }

    @Serializable
    @org.ktorm.ksp.api.Table("manager_list")
    data class Manager(
        val name: String,
        val email: String,

        @Contextual
        val date: LocalDate
    )

    @Serializable
    @org.ktorm.ksp.api.Table("employee")
    data class Employee(
        val id: Int,
        var name: String,
        var pass: String,
        var identity: String,
        var email: String,
        var phone: String,
        var idNumber: String,

        @Contextual
        var date: LocalDate
    )

    @Serializable
    @org.ktorm.ksp.api.Table("book_info")
    data class Book(
        @PrimaryKey
        val bookId: Int,

        var bookCode: String,
        var bookTitle: String,
        var bookArtist: String,

        var bookMainType: String,
        var bookSecondType: String,

        var bookDescription: String,
        var bookPrice: Float,

        var bookBorrowingAllowed: Boolean,
        var bookBan: Boolean,
        var bookHighValue: Boolean,

        var bookOperator: String,
    )
}
```

**Comment by lookup-cat** [comment]
感谢耐心回复, 可惜我这边试了还是复现不出来. 也许触发异常的原因不单独是在这一个文件, 还有其他因素
